### ISSUE TITLE
What was the refernce_shape for pre-trained model ( patch based AAM using SIFT)

### ISSUE THREAD

**Issue by gp1313** [menpo/menpofit#102]

**Comment by jabooth** [comment]
@gp1313 the code used to train the pre-trained model is something we haven't open sourced yet (it's a notebook that depends on lots of internal Imperial network shares/datasets). 

But in general, this AAM was trained using standard datasets, and using a completely unmodified copy of `menpofit` - so the `reference_shape` will have been the mean of the annotations we used in training the model. This is of course dependent on the exact settings we used for the AAM (e.g. `normalize_diagonal`).

Hope that helps? What is it you were hoping to do with the knowledge of the source of the reference space?

**Comment by gp1313** [comment]
@jabooth I have analyzed the performance of pre-trained model on my personal set of test images. I was hoping to train a new model with same parameter as mentioned in documents, and use same dataset mentioned as well. My ultimate goal is to generate new model (from scratch) using menpofit which is similar to pre-trained model w.r.t there performance.

**Comment by gp1313** [comment]
@nontas got it. It does help, Thanks!!
