### ISSUE TITLE
Save Fitter

### ISSUE THREAD

**Issue by dav92lee** [menpo/menpofit#104]
Hello friends!

I was wondering if there's a means to save a given fitter after training it so on next load of the program, I don't have to retrain the fitter.  Was looking through `fitter.py` but didn't find any leads.  Was wondering if this is possible/if I could make this into a feature request.

Thanks a bunch & hope you have a great day!

**Comment by nontas** [comment]
Hi!

You can use [`menpo.io.export_pickle()`](http://docs.menpo.org/en/stable/api/io/export_pickle.html) and [`menpo.io.import_pickle()`](http://docs.menpo.org/en/stable/api/io/import_pickle.html) to save and load, respectively. For example:

```python
import menpo.io as mio
mio.export_pickle(fitter, '/path/to/save/model.pkl')
```

and then
```python
fitter = mio.import_pickle('/path/to/save/model.pkl')
```

**Comment by dav92lee** [comment]
Thanks man!
