### ISSUE TITLE
dlib wrapper error

### ISSUE THREAD

**Issue by georgesterpu** [menpo/menpofit#109]
Hello,

I get this error when using the DlibWrapper with multiprocessing.Pool:

`RuntimeError: Pickling of "dlib.shape_predictor_training_options" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)`

My code is:
```
with Pool(self._nThreads) as p:
    p.starmap(_process_one_file,
              zip(files, repeat(processor)))
```
where `processor` is an instance of a class where one of the members could be a `menpofit.dlib.DlibWrapper`. Code runs fine when that member is instead a `menpofit.aam.LucasKanadeAAMFitter`, or when I don't use `multiprocessing.Pool` at all.

Could you help me find a solution to this problem, while still keeping the benefits of multiple processes ?

Thank you

**Comment by patricksnape** [comment]
We'd have to fix it on the dlib side by updating the library to make the shape predictor training options pickleable. What's easier is that you update your `_process_one_file` function to take the arguments to dlib and create the `shape_predictor_training_options` per process.

**Comment by georgesterpu** [comment]
Thanks Patrick, I've moved the code to load the pre-trained ERT model outside the constructor (that was creating a `processor` instance). Never went deeper into multiprocessing.Pool to learn the working mechanism.
