### ISSUE TITLE
SDMs are not pickleable

### ISSUE THREAD

**Issue by patricksnape** [menpo/menpofit#22]
This is due to the [features](https://github.com/menpo/menpofit/blob/ca83437d00c09b175f21e9a988378d8f3dca8a9f/menpofit/regression/trainer.py#L90) method on the ``RegressionTrainer`` class/subclasses. For the `NonParameterRegressorTrainer`, the [features](https://github.com/menpo/menpofit/blob/ca83437d00c09b175f21e9a988378d8f3dca8a9f/menpofit/regression/trainer.py#L296) method is passed into the `NonParametricRegressor` [here](https://github.com/menpo/menpofit/blob/ca83437d00c09b175f21e9a988378d8f3dca8a9f/menpofit/regression/trainer.py#L181), which is a bound method. This can't be pickled. Therefore, we need to break that dependency and make that features method a separate function or a Callable.

**Comment by grigorisg9gr** [comment]
Closed with https://github.com/menpo/menpofit/pull/55 right?

**Comment by patricksnape** [comment]
Yup :)
