### ISSUE TITLE
handle trilist deprecation in menpo image in menpofit

### ISSUE THREAD

**Issue by jabooth** [menpo/menpofit#28]
We need to check through the use of trilist here (as it's now deprecated in menpo)
https://github.com/menpo/menpofit/blob/master/menpofit/aam/builder.py#L607

**Comment by patricksnape** [comment]
This has been fixed and warning is now [raised](https://github.com/menpo/menpofit/blob/e87715dfa7019da88efb6ca15bcd06fb75c79d0a/menpofit/aam/base.py#L90).
