### ISSUE TITLE
noisy_shape_from_shape rotation parameter

### ISSUE THREAD

**Issue by patricksnape** [menpo/menpofit#69]
Is the `rotation` parameter of `noisy_shape_from_shape` correct? At the moment it controls if the initial `AlignmentSimilarity` accounts for rotation or not. Then, it will generate an initial shape that **does perturb the rotation**. I feel like the `rotation` parameter should control whether or not the noisy shape contains rotation or not. This seems to be what is commonly done in the face alignment literature - only generate perturbations that contain scale and translation variation.

@jalabort thoughts?

**Comment by jalabort** [comment]
I like to have the freedom of being able to perturb the rotation parameter without having to align with rotation to the ground truth. However, maybe we could change the defaults in `noisy_shape_from_shape` so that `noise_percentage=[0.1, 0, 0.1]` and the perturbation over the rotation parameter does not happen by default.

**Comment by patricksnape** [comment]
Oh! I feel a fool now, I didn't realise I could pass a list :+1: Why would you want to perform the initial alignment without rotation? Even so, perhaps we should make this more clear by parameter naming? Something like ``allow_alignment_rotation`` or something?

**Comment by jalabort** [comment]
Renaming to `allow_alignment_rotation` sounds good to me. Regarding your question, in SDM training aligning without rotation and generating rotation perturbations makes sure you adapt to the kind of rotations present in your training dataset while allowing also to adapt to arbitrary rotations that are not naturally present. I'm on really fine grain here... but in theory this gives you more freedom regarding what exactly you want to learn...

**Comment by patricksnape** [comment]
OK - well I'll rename that parameter and then I'm actually happy with this.

**Comment by patricksnape** [comment]
@nontas - can we make this fix in your PR as well?

**Comment by nontas** [comment]
Done in https://github.com/menpo/menpofit/pull/83 .
