### ISSUE TITLE
Make the n_components behaviour clear for models (AAMs etc)

### ISSUE THREAD

**Issue by patricksnape** [menpo/menpofit#82]
As kindly pointed out by @graebson, it is currently unclear how the interaction between `max_n_components` and `n_shape`/`n_appearance` works when proportional variances are chosen. After discussing with @graebson and @jabooth it is probably fine how it works, however, it definitely needs to be documented better.

**Comment by patricksnape** [comment]
@nontas We probably should make sure this is clarified too (before #83 is merged).

**Comment by nontas** [comment]
Done
